name: 🙋 Help
description: Open an issue and request for individual help
labels: ['help wanted']

body:
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
      - label: I have written a descriptive issue title
        required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js version
      placeholder: 14.x
    validations:
      required: true

  - type: textarea
    id: text
    attributes:
      label: Issue
      description: |
        Give as much detail as you can to help us understand.
        Make sure you place example code inside a [code (```) block](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) to avoid linking unrelated issues.
